In [1]:
import numpy as np
from pypianoroll import Multitrack, Track
from matplotlib import pyplot as plt


KeyboardInterrupt: 

In [ ]:
import os
print (os.getcwd())
print(os.getcwd())

In [ ]:
all_track=[]

In [ ]:
i=0
k=0
c=20000
import pickle
f=[]
#kkl=open(os.getcwd()+'\\data\\data1.pkb', 'w')
for i in range(100):
    f.append(open(os.getcwd()+'\\data\\data{}.pkb'.format(i), 'wb'))
#f.append(open(os.getcwd()+'\\data\\data1.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data2.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data3.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data4.pkb', 'wb'))
"""
f1=open('/data/data1.pkb', 'wb')
f2=open('/data/data2.pkb', 'wb')
f3=open('/data/data3.pkb', 'wb')
f4=open('/data/data4.pkb', 'wb')
"""
#f[0].write('asdfasdf')

file=open('file_path2.txt','rb')

for line in file:
    i=i+1    
    c=c-1
    if c%100==0:
        print(c/100)
#    print(c)
    #print(line[:-2].decode('utf-8'))
    loaded = Multitrack(line[:-2].decode('utf-8'))
    #print(loaded)
    all_track.append(loaded)
    if i%200==0:
        pickle.dump(all_track,f[k])
        k=k+1
        all_track=[]
file.close()

In [3]:
print(loaded)
print(type(loaded.tracks))

tracks : [Drums, Piano, Guitar, Bass, Strings],
tempo : [102.000051 102.000051 102.000051 ...  64.        64.        64.      ],
downbeat : [ True False False ... False False False],
beat_resolution : 24,
name : 38bc689601e4e45c061cf6b18443b5e7
<class 'list'>


In [4]:
# analizing notes
#input a Multitrack object 
#ex:
#another_multitrack = Multitrack('./data2/rock-39.mid')
#note_distribution(another_multitrack)
#return note_distribution of the whole song which order is C #C D #D ... bB B

def note_distribution(another_multitrack):
    #notes_per_beat is the minus 24 mod14 product C(Do) to be zero is better for the further task
    notes_per_beat=[]
    length=len(another_multitrack.get_merged_pianoroll())
    merged=another_multitrack.get_merged_pianoroll()
    print(merged)

    for i in range(length):
        if (length-i)%1000==0:
            print(length-i)
        #print('ori',np.nonzero(another_multitrack.get_merged_pianoroll()[i])[0])
        temp=list(np.nonzero(merged[i])[0])              
        for j in range(len(temp)):
            temp[j]=(temp[j]-24)%12
        notes_per_beat.append(temp)
        #print(temp)
        #print('new',temp)
        #print(list(np.nonzero(another_multitrack.get_merged_pianoroll()[i])[0])+1)
    #np.nonzero(another_multitrack.get_merged_pianoroll())
    length=len(another_multitrack.get_merged_pianoroll())
    note_distributions=[]
    for i in range(12):
        note_distributions.append(0)
    print(note_distributions)
    for i in range(length):
        #print(notes_per_beat[i])
        for j in range(12):
            #print(j,notes_per_beat[i].count(j))
            note_distributions[j]= notes_per_beat[i].count(j)+note_distributions[j]
    print(note_distributions)
    sum=0
    for ele in note_distributions:
        sum=sum+ele
    note_distribution_frequency=[]
    for ele in note_distributions:
        note_distribution_frequency.append(ele/sum)
    
    return note_distributions,note_distribution_frequency
note_distribution(loaded)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[4519, 1907, 11618, 401, 7819, 8, 7251, 8513, 1830, 9111, 100, 7655]


([4519, 1907, 11618, 401, 7819, 8, 7251, 8513, 1830, 9111, 100, 7655],
 [0.07440887835078706,
  0.03140025027991833,
  0.1912994796812224,
  0.006602779424356188,
  0.12874596588289533,
  0.00013172627280511097,
  0.11939340051373247,
  0.14017322004873872,
  0.030132384904169137,
  0.15001975894092076,
  0.0016465784100638872,
  0.12604557729039056])