In [19]:
import numpy as np
from pypianoroll import Multitrack, Track
from matplotlib import pyplot as plt


In [20]:
import os
print (os.getcwd())
print(os.getcwd())

C:\Users\ailab\1projects\MusicGan\styleMuseGAN
C:\Users\ailab\1projects\MusicGan\styleMuseGAN


In [21]:
all_track=[]

In [22]:
i=0
k=0
c=20000
import pickle
f=[]
#kkl=open(os.getcwd()+'\\data\\data1.pkb', 'w')
for i in range(100):
    f.append(open(os.getcwd()+'\\data\\data{}.pkb'.format(i), 'wb'))
#f.append(open(os.getcwd()+'\\data\\data1.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data2.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data3.pkb', 'wb'))
#f.append(open(os.getcwd()+'\\data\\data4.pkb', 'wb'))
"""
f1=open('/data/data1.pkb', 'wb')
f2=open('/data/data2.pkb', 'wb')
f3=open('/data/data3.pkb', 'wb')
f4=open('/data/data4.pkb', 'wb')
"""
#f[0].write('asdfasdf')

file=open('file_path2.txt','rb')

for line in file:
    i=i+1    
    c=c-1
    if c%100==0:
        print(c/100)
#    print(c)
    #print(line[:-2].decode('utf-8'))
    loaded = Multitrack(line[:-2].decode('utf-8'))
    #print(loaded)
    all_track.append(loaded)
    if i%200==0:
        pickle.dump(all_track,f[k])
        k=k+1
        all_track=[]
file.close()

199.0


KeyboardInterrupt: 

In [ ]:
print(loaded)
print(type(loaded.tracks))

In [26]:
# analizing notes
#input a Multitrack object 
#ex:
#another_multitrack = Multitrack('./data2/rock-39.mid')
#note_distribution(another_multitrack)
#return note_distribution of the whole song which order is C #C D #D ... bB B

def note_distribution(another_multitrack):
    #notes_per_beat is the minus 24 mod14 product C(Do) to be zero is better for the further task
    notes_per_beat=[]
    length=len(another_multitrack.get_merged_pianoroll())
    merged=another_multitrack.get_merged_pianoroll()
    print(merged)

    for i in range(length):
        if (length-i)%1000==0:
            print(length-i)
        #print('ori',np.nonzero(another_multitrack.get_merged_pianoroll()[i])[0])
        temp=list(np.nonzero(merged[i])[0])              
        for j in range(len(temp)):
            temp[j]=(temp[j]-24)%12
        notes_per_beat.append(temp)
        #print(temp)
        #print('new',temp)
        #print(list(np.nonzero(another_multitrack.get_merged_pianoroll()[i])[0])+1)
    #np.nonzero(another_multitrack.get_merged_pianoroll())
    length=len(another_multitrack.get_merged_pianoroll())
    note_distributions=[]
    for i in range(12):
        note_distributions.append(0)
    #print(note_distributions)
    for i in range(length):
        #print(notes_per_beat[i])
        for j in range(12):
            #print(j,notes_per_beat[i].count(j))
            note_distributions[j]= notes_per_beat[i].count(j)+note_distributions[j]
    #print(note_distributions)
    sum=0
    for ele in note_distributions:
        sum=sum+ele
    note_distribution_frequency=[]
    for ele in note_distributions:
        note_distribution_frequency.append(ele/sum)
    
    return note_distributions,note_distribution_frequency
note_distribution(loaded)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000


([5139, 16231, 0, 19003, 393, 1355, 6233, 1, 10976, 2, 14233, 4606],
 [0.0657396510259428,
  0.2076318886557847,
  0.0,
  0.24309215575909532,
  0.005027375530880622,
  0.017333572123010798,
  0.07973443176584967,
  1.2792304149823466e-05,
  0.14040833034846237,
  2.5584608299646932e-05,
  0.1820728649644374,
  0.058921352914086886])

In [25]:
file=open('file_path2.txt','rb')
i=0
note_dis=[]
for line in file:
    i=i+1    
    #c=c-1
    #if c%100==0:
        #print(c/100)
#    print(c)
    #print(line[:-2].decode('utf-8'))
    loaded = Multitrack(line[:-2].decode('utf-8'))
    #print(loaded)
    #file_names.append(line[:-2].decode('utf-8'))
    note_dis.append(note_distribution(loaded))
    """
    if i%200==0:
        pickle.dump(all_track,f[k])
        k=k+1
        all_track=[]
    """
    

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[7215, 8, 7598, 0, 3028, 7203, 1241, 8557, 0, 8972, 0, 3465]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3089, 29, 2559, 1252, 1913, 2311, 1884, 2178, 368, 1145, 2043, 426]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[6519, 956, 9053, 255, 7769, 2678, 1911, 8742, 528, 8665, 63, 6068]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0,

KeyboardInterrupt: 

Exception ignored in: 'zmq.backend.cython.message.Frame.__dealloc__'
Traceback (most recent call last):
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
    PyErr_CheckSignals()
KeyboardInterrupt


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1046, 600, 8015, 6, 7408, 1215, 7625, 5406, 61, 7910, 577, 6291]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[296, 9910, 9515, 3020, 15185, 262, 10133, 72, 3792, 13372, 437, 9197]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1014, 1857, 13854, 256, 3609, 119, 7676, 4591, 1111, 9105, 212, 6321]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3787, 484, 2647, 419, 4170, 2596, 437, 2185, 1105, 5218, 10, 3704]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]

[19643, 126, 9565, 624, 5515, 13461, 694, 7872, 774, 19220, 12496, 131]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3258, 5249, 90, 2988, 138, 3276, 1545, 188, 5944, 1, 2931, 249]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2934, 1030, 2150, 1090, 1772, 3773, 120, 2535, 803, 3041, 2436, 765]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[18225, 782, 2649, 239, 2143, 11104, 112, 7054, 376, 3119, 7983, 254]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6000
5000
4000
3000
2000
1000
[0, 0,

[5907, 35, 2994, 0, 2518, 4011, 174, 5320, 164, 3382, 27, 3373]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[6363, 0, 5585, 3272, 1549, 6987, 65, 9506, 4644, 224, 12354, 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[4954, 42, 278, 0, 4846, 1080, 271, 1826, 182, 6814, 266, 1401]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[4897, 99, 5581, 3609, 192, 5399, 478, 4376, 18, 1605, 7902, 206]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
11000
10000
9000
80

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2016, 472, 3070, 325, 3450, 809, 2005, 2903, 138, 2167, 713, 4926]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1117, 2529, 1702, 2057, 3399, 2341, 4062, 694, 1538, 2889, 3364, 3193]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[17638, 28, 13623, 13, 13435, 107, 606, 27532, 3, 15865, 649, 14746]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15000
14000
13000
12000
11000
10000
9000
8000
7000
6000
5000
4000
3000
2000
1000


KeyboardInterrupt: 

In [6]:
print(file_names[:5])


['C:\\Users\\ailab\\1projects\\MusicGan\\styleMuseGAN\\lpd_5_cleansed\\lpd_5\\lpd_5_cleansed\\A\\A\\A\\TRAAAGR128F425B14B\\b97c529ab9ef783a849b896816001748.npz', 'C:\\Users\\ailab\\1projects\\MusicGan\\styleMuseGAN\\lpd_5_cleansed\\lpd_5\\lpd_5_cleansed\\A\\A\\A\\TRAAAZF12903CCCF6B\\05f21994c71a5f881e64f45c8d706165.npz', 'C:\\Users\\ailab\\1projects\\MusicGan\\styleMuseGAN\\lpd_5_cleansed\\lpd_5\\lpd_5_cleansed\\A\\A\\B\\TRAABXH128F42955D6\\04266ac849c1d3814dc03bbf61511b33.npz', 'C:\\Users\\ailab\\1projects\\MusicGan\\styleMuseGAN\\lpd_5_cleansed\\lpd_5\\lpd_5_cleansed\\A\\A\\C\\TRAACQE12903CC706C\\f1be134b947dfde3eece2861546ffd82.npz', 'C:\\Users\\ailab\\1projects\\MusicGan\\styleMuseGAN\\lpd_5_cleansed\\lpd_5\\lpd_5_cleansed\\A\\A\\D\\TRAADKW128E079503A\\72cae5077339f6abaee4cad318b1e923.npz']


Multitrack(tracks=['Drums', 'Piano', 'Guitar', 'Bass', 'Strings'], tempo=array([122.00180563, 122.00180563, 122.00180563, ..., 122.00180563,
       122.00180563, 122.00180563]), downbeat=array([ True, False, False, ..., False, False, False]), beat_resolution=24, name=b97c529ab9ef783a849b896816001748)

In [15]:
import tensorflow as tf

def _parse_function(filename):
    loaded=Multitrack(filename)
    _,frequency=note_distribution(load)
    return frequency

# 图片文件的列表
"""
tf.convert_to_tensor(
    value,
    dtype=None,
    name=None,
    preferred_dtype=None
)
"""
filenames=tf.convert_to_tensor(file_names)
"""
filenames= = tf.constant(["/var/data/image1.jpg", "/var/data/image2.jpg", ...])
# label[i]就是图片filenames[i]的label
labels = tf.constant([0, 37, ...])

# 此时dataset中的一个元素是(filename, label)
dataset = tf.data.Dataset.from_tensor_slices((filenames, labels))

# 此时dataset中的一个元素是(image_resized, label)
dataset = dataset.map(_parse_function)

# 此时dataset中的一个元素是(image_resized_batch, label_batch)
dataset = dataset.shuffle(buffersize=1000).batch(32).repeat(10)
"""


'\nfilenames= = tf.constant(["/var/data/image1.jpg", "/var/data/image2.jpg", ...])\n# label[i]就是图片filenames[i]的label\nlabels = tf.constant([0, 37, ...])\n\n# 此时dataset中的一个元素是(filename, label)\ndataset = tf.data.Dataset.from_tensor_slices((filenames, labels))\n\n# 此时dataset中的一个元素是(image_resized, label)\ndataset = dataset.map(_parse_function)\n\n# 此时dataset中的一个元素是(image_resized_batch, label_batch)\ndataset = dataset.shuffle(buffersize=1000).batch(32).repeat(10)\n'

In [17]:
dataset = tf.data.Dataset.from_tensor_slices((filenames))
dataset = dataset.map(lambda string: Multitrack(string))


AttributeError: 'Tensor' object has no attribute 'endswith'

In [ ]:
"""
def _parse_function(filename):
  image_string = tf.read_file(filename)
  image_decoded = tf.image.decode_image(image_string)
  image_resized = tf.image.resize_images(image_decoded, [28, 28])
  return image_resized, label
"""
